### ISSUE TITLE
Word2vec features

### ISSUE THREAD

**Issue by aranciokov** [mwray/Joint-Part-of-Speech-Embeddings#1]
Dear Michael, thanks for releasing the code for JPoSE. I have a question about the textual features used for Epic-Kitchens 100. 
I would like to use part of scripts/create_feature_files.py but it requires a word2vec model. I tried looking for a wikipedia-pretrained (as is mentioned in the [paper](https://arxiv.org/pdf/2006.13256.pdf)) with 200-D vectors but I can not seem to find any. Would it be possible for you to share the one you used? 
Thanks, 
Alex

**Comment by mwray** [comment]
Hi Alex,

I've uploaded the model to dropbox, it can be found [here](https://www.dropbox.com/s/f2f85nqadv3cmkm/wiki_new.zip?dl=0).

Thanks,
Mike
